module.exports = {
    up: async (queryInterface, Sequelize) => {
        await queryInterface.bulkInsert('user', [
            {
                name: 'Martin',
                surname: 'Garcia',
                email: 'martin@gmail.com',
                age: new Date('09-10-1995'),
                phoneNumber: '+34689654301',
                profileImg: '',
                password: 'libnub1290pUU',
                isAdmin: false,
                isOwner: false,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Carlos',
                surname: 'Aparicio',
                email: 'carlosAp@gmail.com',
                age: new Date('06-12-1990'),
                phoneNumber: '+34689339301',
                profileImg: '',
                password: 'ECpVh7Gah4zjXgWE',
                isAdmin: false,
                isOwner: false,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Pedro',
                surname: 'Sarrion',
                email: 'pedroSa@gmail.com',
                age: new Date('10-01-1992'),
                phoneNumber: '+34689875430',
                profileImg: '',
                password: '3M6RPE9jx6PLC7S3',
                isAdmin: false,
                isOwner: false,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Jose',
                surname: 'Piqueras',
                email: 'JosePiq@gmail.com',
                age: new Date('02-06-2000'),
                phoneNumber: '+34689612301',
                profileImg: '',
                password: 'WA9cHaIwFCwqHNuv',
                isAdmin: false,
                isOwner: false,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Alex',
                surname: 'Gonzalez',
                email: 'Alexgg@gmail.com',
                age: new Date('20-08-1999'),
                phoneNumber: '+34682198301',
                profileImg: '',
                password: 'VhHcAK4Zch7CuJxY',
                isAdmin: false,
                isOwner: false,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Abel',
                surname: 'Lopez',
                email: 'abelLP@gmail.com',
                age: new Date('02-08-1997'),
                phoneNumber: '+34689654391',
                profileImg: '',
                password: 'dMKwMHCSaYnXzNDa',
                isAdmin: false,
                isOwner: false,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Miguel',
                surname: 'Sanchez',
                email: 'miguelSS@gmail.com',
                age: new Date('06-12-1998'),
                phoneNumber: '+34634764301',
                profileImg: '',
                password: '5cLKVWSakGrSkqEf',
                isAdmin: false,
                isOwner: false,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Sandro',
                surname: 'Pedron',
                email: 'sandroo@gmail.com',
                age: new Date('10-05-2001'),
                phoneNumber: '+34659824301',
                profileImg: '',
                password: 'z6Mthtbkp34qDGE5',
                isAdmin: false,
                isOwner: false,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Luis',
                surname: 'Garcia',
                email: 'LuisGg@gmail.com',
                age: new Date('10-06-1985'),
                phoneNumber: '+34682345601',
                profileImg: '',
                password: '7WuDL4YR9S46ZTeQ',
                isAdmin: false,
                isOwner: false,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Hector',
                surname: 'Perez',
                email: 'hectorP@gmail.com',
                age: new Date('12-04-2002'),
                phoneNumber: '+34689789501',
                profileImg: '',
                password: '35aLL5YAFnWVqQJv',
                isAdmin: false,
                isOwner: false,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Marta',
                surname: 'Aguilar',
                email: 'martaat@gmail.com',
                age: new Date('31-10-1992'),
                phoneNumber: '+34679798761',
                profileImg: '',
                password: 'rxH6WXPXX37FYFjb',
                isAdmin: true,
                isOwner: false,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Maria',
                surname: 'Sampedro',
                email: 'mariaSp@gmail.com',
                age: new Date('03-06-1988'),
                phoneNumber: '+34688723301',
                profileImg: '',
                password: 'YsKbggWkn7SX7zYH',
                isAdmin: false,
                isOwner: false,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Carmen',
                surname: 'Simon',
                email: 'carmenSS@gmail.com',
                age: new Date('03-04-1993'),
                phoneNumber: '+34689676121',
                profileImg: '',
                password: 'uTsFtZsdywyEYhgY',
                isAdmin: false,
                isOwner: false,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Patricia',
                surname: 'Garcia',
                email: 'patgarc@gmail.com',
                age: new Date('03-05-1997'),
                phoneNumber: '+34654544301',
                profileImg: '',
                password: 'eKcgKNu3aQqGmSMX',
                isAdmin: false,
                isOwner: false,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Begoña',
                surname: 'Diaz',
                email: 'begodiaz@gmail.com',
                age: new Date('22-10-2003'),
                phoneNumber: '+34689123451',
                profileImg: '',
                password: 'MESsqMGG333BhVVv',
                isAdmin: false,
                isOwner: false,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Andrea',
                surname: 'Jimenez',
                email: 'andji@gmail.com',
                age: new Date('25-09-1998'),
                phoneNumber: '+34689234561',
                profileImg: '',
                password: 'tm8eQgT5dPqSUpQa',
                isAdmin: false,
                isOwner: false,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Sandra',
                surname: 'Gomez',
                email: 'sandri@gmail.com',
                age: new Date('23-07-2003'),
                phoneNumber: '+34689345671',
                profileImg: '',
                password: 'RCHxZF57hajgZ9vG',
                isAdmin: false,
                isOwner: false,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Laura',
                surname: 'Lopez',
                email: 'Laulo@gmail.com',
                age: new Date('06-12-1999'),
                phoneNumber: '+34686789301',
                profileImg: '',
                password: 'cSAMsxTDFFXBzF5w',
                isAdmin: false,
                isOwner: false,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Paula',
                surname: 'Moreno',
                email: 'pauMoreno@gmail.com',
                age: new Date('12-07-2000'),
                phoneNumber: '+34689098761',
                profileImg: '',
                password: 't686t7rwjqBBdUGE',
                isAdmin: false,
                isOwner: false,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Aina',
                surname: 'Ruiz',
                email: 'ainruiz@gmail.com',
                age: new Date('10-03-1985'),
                phoneNumber: '+34689129851',
                profileImg: '',
                password: 'fqkerzPYs6NCPKLF',
                isAdmin: false,
                isOwner: false,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
        ]);
    },
    down: async (queryInterface, Sequelize) => {
        await queryInterface.bulkDelete('user', null, {});
    },
};
